version: '3.6'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /postgres-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD="***REMOVED***"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready --username postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  web:
#    image: mrfleap/esprza
    build: .
    command: ./start.sh
    restart: always
    env_file:
      - env.list
    depends_on:
    - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 30s
      retries: 4